version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sample_db
      MYSQL_USER: sample_user
      MYSQL_PASSWORD: sample_password
    ports:
      - "33006:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
